### PR TITLE
Hello world: new Knack > 311 integration script

### PR DESCRIPTION
**Pull request by johnclary**
## Associated issue

- https://github.com/cityofaustin/atd-data-tech/issues/11175

This PR serves as a place to review this new script, which replaces these two legacy scripts:
- https://github.com/cityofaustin/atd-data-publishing/blob/production/transportation-data-publishing/data_tracker/esb_xml_gen.py
- https://github.com/cityofaustin/atd-data-publishing/blob/production/transportation-data-publishing/data_tracker/esb_xml_send.py

There is a related PR in the atd-prefect for deployment - [#53](https://github.com/cityofaustin/atd-prefect/pull/53).

## Steps to test

1. Prepare test records in the Data Tracker's test environment - `TEST - ESB ENV - AMD Data Tracker | 19 APR 2022`: navigate to the [`tmc_activities` object](https://builder.knack.com/atd/austin-transportation-data-tracker-esb-test-environment-20/records/objects/object_75). 

2. Select activities with ID's 1 & 2, and use the **Update** tool to set the **PROCESS_STATE_ESB** field to **READY_TO_SEND**

Screen Shot 2023-02-03 at 11 56 02 AM

3. Now you're ready to run the script. Pull (or build) the docker image: `atddocker/atd-knack-311:staging`

4. Configure an environment file which has the Data Tracker test environment credentials and the ESB - Test endpoint. See the "Environment for atd-knack-311" item in our password store.

5. Save a copy of self-signed SSL key and certificate in the root of this repository as `esb.pem` and `esb.cert`. You can locate these files by searching the password store for "atd-knack-311 self-signed". 

6. Run the script, mounting your local clone of the repo (with certs) into the container

```
$ docker run -it --rm --env-file env_file -v "$(pwd)":/app atddocker/atd-knack-311:staging python send_knack_messages_to_esb.py data-tracker
```

7. Refresh the Knack builder and observe that the two records you recently modified now have an **ESB_PROCESS_STATUS**  of **SENT**.

### CODE REVIEW

**Comment by frankhereford** [comment]
John, in this PR, in your instructions - there is a invocation of the `:production` tagged docker image and an instruction to build / pull the `:staging` tagged image. Super no big deal, very easy to work around, (i'm building it with my own wacky tag, for example), but I wanted to point it out in case anyone else got snagged by that. Please let me know if I'm misunderstanding though - thanks!!!

**Comment by johnclary** [comment]
thanks @frankhereford and sorry for that confusion — i updated the command in step #6

**Review by frankhereford — APPROVED** [review]
John, this worked great on the first shot. 🎯 Thanks for the helpful instructions on how to prepare the environment and how to get the knack records in the right state. 

Thanks for revisiting these scripts and for writing this new version of them. It looks great, and it's super readable and well documented. This will be very helpful next time the 311 / knack integration does something unexpected. 🙌 🔥

🚀🚀🚀🚀


* I wanted to confirm that we don't have visibility into if the ESB successfully beyond the HTTP code that is checked in the `res.raise_for_status()` call on line 147? I'm not suggesting that there needs to be one, or even could be one, just to double check that I didn't miss it.

* I observe that you have the `SPECIAL_CHAR_LOOKUP` table to encode those 5 special characters. Is that an exhaustive list of stuff that needs to be escaped? Maybe something from [xml.sax.saxutils](https://docs.python.org/3/library/xml.sax.utils.html) might be helpful? I  really think there is a strong possibility I'm bring up a question about something that isn't broken, isn't fragile and is totally the most clear way to do it - you probably want to ignore this comment.

* I've just spent a bit trying to understand the `*`-on-its-own that you've included to denote acceptance of an iterable in your definition of `send_message()` on line 124. I'm sure it's fine, I just don't think I fully understand it - maybe I'm not reading the right docs. It's a tricky one to search for, that's for sure. Maybe I can bug you in an upcoming dev sync to explain more about what is happening there; it'll be a TIL for me, no doubt.

**Review by mddilley — APPROVED** [review]
Tested this out with the ESB test Knack app, and it works just as you described. The new script looks great too! I tripped up for just a second when I realized that I needed to be on VPN to reach `esbtest.austintexas.gov`, but the errors led me straight to the answer. 🚢 🚀 

@frankhereford - _I think_ [this](https://stackoverflow.com/questions/2965271/forced-naming-of-parameters-in-python/14298976#14298976) answers your question about `*` in the function parameters. That was a TIL for me! 🐍

**Review by chiaberry — APPROVED** [review]

**Comment by johnclary** [comment]
thanks y'all! it is finally time to merge this 😅

**Pull request merged**
