### PR TITLE
use a difrerenct acitvitiy code for closing an issue

### PR DESCRIPTION
**Pull request by johnclary**
Patrick @ 311 says we need to do this instead

### CODE REVIEW

**Review by chiaberry — APPROVED** [review]
ok. is there somewhere to look up activity codes, or will Robert just let us know which ones to use?

**Review by Charlie-Henry — APPROVED** [review]
CLOISSRE sounds like a pokemon 🚢

**Comment by johnclary** [comment]
catch em all (the bugs, that is)

**Comment by johnclary** [comment]
> ok. is there somewhere to look up activity codes, or will Robert just let us know which ones to use?

@chiaberry just notice your question. Patrick @ 311 tells is gives us the name of the activity codes that we can/should use.

**Pull request merged**
